### ISSUE TITLE
TypeError: (0 , _gsheetsapi.default)(...).then is not a function in gsheetsapi.js

### ISSUE THREAD

**Issue by DevendraKumarL** [bpk68/g-sheets-api#17]
Below is the error when I try to use the g-sheets-api in my nodejs app:

```
const gsheetsReader = require('g-sheets-api');
app.get('/gsheets', (request, response) => {
	gsheetsReader({ sheetId: sheetId }, results => {
		response.send(results)
	}, error => {
		console.log(error);
		response.send([]);
	});
});
```

```
TypeError: (0 , _gsheetsapi.default)(...).then is not a function
    at gsheetProcessor (C:\github\web-apps\hobbit-tracker\node_modules\g-sheets-api\dist\gsheetsprocessor.js:113:45)
    at reader (C:\github\web-apps\hobbit-tracker\node_modules\g-sheets-api\dist\index.js:13:33)
    at app.get (C:\github\web-apps\hobbit-tracker\server.js:20:2)
    at Layer.handle [as handle_request] (C:\github\web-apps\hobbit-tracker\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\github\web-apps\hobbit-tracker\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\github\web-apps\hobbit-tracker\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\github\web-apps\hobbit-tracker\node_modules\express\lib\router\layer.js:95:5)
    at C:\github\web-apps\hobbit-tracker\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\github\web-apps\hobbit-tracker\node_modules\express\lib\router\index.js:335:12)
    at next (C:\github\web-apps\hobbit-tracker\node_modules\express\lib\router\index.js:275:10)
```

To resolve this I'm adding the node-fetch npm package and adding this line at the top of gsheetsapi.js:
`const fetch = require('node-fetch');`

I forked the repo and ran the g-sheet-apis locally and it worked without any issue.

Any idea why I need to do this when using it in my node app?

**Comment by bpk68** [comment]
Hey @DevendraKumarL 

Sorry you're having issues with this. I can't see an issue with the sheets reader itself. It runs locally and also in this little demo I put together using the latest release -> https://codesandbox.io/s/g-sheets-reader-demo-qm5r0

It could be an issue with your app, especially if it's using node, you would need to add in fetch, as you have done. 

For a regular JS app, it should work without an issue.

I'll close this for now, but if you come across any other problems then let me know 😄

**Comment by DevendraKumarL** [comment]
I'm not sure what is wrong with my node project. But I am seeing the same error when I try to use the npm package in RunKit https://runkit.com/embed/0iiz47dhura9.  I tried a plain nodeJs demo too https://codesandbox.io/s/mutable-grass-sudnx.
